### ISSUE TITLE
Build errors on latest commit

### ISSUE THREAD

**Issue by brunoanc** [Anatdx/HymoFS#15]
After updating my GKI kernel to 21e131f (from the 6.6 branch) and trying to build using the bazel system, I got the following errors:

```
   ERROR: /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/BUILD.bazel:149:22: Building kernel (lto=thin;trim) @@//common:kernel_aarch64 failed: (Exit 2): bash failed: error executing KernelBuild command (from target //common:kernel_aarch64) /bin/bash -c ... (remaining 1 argument skipped)
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/fs/hymofs.c:365:19: error: unused variable 'flags' [-Werror,-Wunused-variable]
    365 |     unsigned long flags;
        |                   ^~~~~
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/fs/hymofs.c:1594:12: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
   1594 |     return test_bit(h1 & HYMO_BLOOM_MASK, filter) & 
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |                                                   &&
   1595 |            test_bit((h1 >> 16) & HYMO_BLOOM_MASK, filter);
        |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/include/linux/bitops.h:61:29: note: expanded from macro 'test_bit'
     61 | #define test_bit(nr, addr)              bitop(_test_bit, nr, addr)
        |                                         ^
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/include/linux/bitops.h:49:2: note: expanded from macro 'bitop'
     49 |         ((__builtin_constant_p(nr) &&                                   \
        |         ^
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/fs/hymofs.c:1594:12: note: cast one or both operands to int to silence this warning
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/include/linux/bitops.h:61:29: note: expanded from macro 'test_bit'
     61 | #define test_bit(nr, addr)              bitop(_test_bit, nr, addr)
        |                                         ^
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/include/linux/bitops.h:49:2: note: expanded from macro 'bitop'
     49 |         ((__builtin_constant_p(nr) &&                                   \
        |         ^
  /home/runner/work/GKI_KernelSU_SUSFS/GKI_KernelSU_SUSFS/android15-6.6-89/common/fs/hymofs.c:2072:19: error: unused variable 'flags' [-Werror,-Wunused-variable]
   2072 |     unsigned long flags;
        |                   ^~~~~
  3 errors generated.
```

These are fixed easily by commenting out or marking with `__maybe_unused` both of the `unsigned long flags` lines, and casting both of the `test_bit`s to `int`. See https://github.com/brunoanc/HymoFS/commit/e3c358463c90d8654e7f096c1b6e9db1536736e2 for reference (I only updated the patch file in my testing).
